#!/bin/bash

# Backs up all files in the current directory modified within the last 24 hours

BACKUPFILE=backup-$(date +%m-%d-%Y)
#		Embeds date in the backup filename
archive=${1:-$BACKUPFILE}
#  If no backup-archive filename specified on command line,
#+ it will default to "backup-MM-DD-YYYY.tar.gz."

tar cvf - `find . -mtime -1 -type f -print` > $archive.tar
gzip $archive.tar
echo "Directory $PWD back up in archive file \"$archive.tar.gz\"."

exit 0
