#!/bin/bash
# Cleanup, version 3
# Advanced bash scripting guide

LOG_DIR=/var/log
ROOT_UID=0	# Only users with $UID 0 have root privilages.
LINES=50	# Default number of lines saved.
E_XCD=86	# Can't change directory?
E_NOTROOT=87	# Non-root exit error.

# Run as root, of course.
if [ "$UID" -ne "$ROOT_UID" ]
then
	echo "Must be root to run this script."
	exit $E_NOTROOT
fi

if [ -n "$1" ]
# Test whether command-line argument is present (non-empty).
then
	lines=$1
else
	lines=$LINES # Default, if not specified on command-line.
fi

cd $LOG_DIR

if [ `pwd` != "$LOG_DIR" ] # check to see if you're in /var/log
then
	echo "Can't change to $LOG_DIR."
	exit $E_XCD
fi  # Ensure you're in the correct directory before messing with the log file

tail -n $lines /var/log/messages > mesg.temp	# Save last section of the log file.
mv mesg.temp /var/log/messages			# Rename it as system log file

cat /dev/null > wtmp
echo "Log files cleaned up."

exit 0
# A zero return value from the script upon exit indicates success to the shell
