#!/bin/bash
# Filename: system-log-monitor
# Author: Kenneth Christian
# Created on: 03-20-2017
# Usage: Using tail to monitor the system log
# -----------------------------


filename=sys.log

cat /dev/null > $filename; echo "Creating / cleaning out file."
#  Creates the file if it does not exist,
#+ and truncates it to zero length if it does.
#  : > filename  and  > filename also work.

tail /var/log/messages > $filename
# /var/log/messages must have world read permission for this to work.

echo "$filename contains tail end of system log."

exit 0
