#!/bin/bash
[ ! $1 ] && echo "usage: newsh <filename>" && exit

if [ -f $1 ] ; then
	vim $1
else
	echo "#!/bin/bash">$1
	echo "# Filename: $1">>$1
	echo "# Author: Kenneth Christian">>$1
	echo "# Created on: $(date +%m-%d-%Y)">>$1
	echo "# -----------------------------">>$1
	echo>>$1
	chmod 755 $1
	vim $1
fi
